development:
  adapter: postgresql
  database: development
  username: vagrant

test:
  adapter: postgresql
  database: test
  template: template0
  username: vagrant

# should be identical to test apart from running on postgres
# NOTE: this can probably be dispensed with once we're developing
# locally under vagrant
travis:
  adapter: postgresql
  database: growstuff_test
  username: postgres

production:
  adapter: postgresql
  database: growstuff_prod
  pool: 5
  timeout: 5000
  username: growstuff
  host: localhost
  password: thisisnottherealpassword

staging:
  adapter: postgresql
  database: growstuff_prod
  pool: 5
  timeout: 5000
  username: growstuff
  host: localhost
  password: thisisnottherealpassword
